require: rubocop-rails

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20
  
AllCops:
  Exclude:
    - 'config/application.rb'
    - 'app/mailers/application_mailer.rb'
    - 'spec/spec_helper.rb'
    - 'app/helpers/application_helper.rb'
    - 'config/**/*.rb'
    - 'bin/**'
   
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/*.rb'
    - 'spec/**/*.rb'
